### ISSUE TITLE
Error when reconnecting arc agent

### ISSUE THREAD

**Issue by strottos** [Azure/AzureConnectedMachineDsc#2]
When reconnecting the arc agent through DSC (say because you've changed resource group for example) it currently throws the following error:
```
VERBOSE: [FOO01]:                            [[AzureConnectedMachineAgentDsc]ConnectToArc] Machine FOO01 is already onboarded. 
 Disconnecting, restarting service, and reconnecting.               Error: unknown flag: --resource-name
    + CategoryInfo          : NotSpecified: (Error: unknown flag: --resource-name:) [], CimException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : foo01

Usage:
  azcmagent disconnect [flags]
Flags:
     --access-token string               Access token
  -f, --force-local-only                  Delete local state only
  -p, --service-principal-secret string   Service Principal Secret
  -v, --verbose   Increase logging verbosity to show all logs
VERBOSE: [FOO01]:                            [[AzureConnectedMachineAgentDsc]ConnectToArc] Attempting to register machine.
The PowerShell DSC resource '[AzureConnectedMachineAgentDsc]ConnectToArc' with SourceInfo
functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : foo01
```

I suspect some arguments were removed from the `azcmagent disconnect` command and in any case there seems to be a simple fix for this which is remove the arguments that are no longer needed. If I've time I will submit a PR for this one.

**Comment by mgreenegit** [comment]
I will do my best to review this week. We are working hard to get DSCv3 out.
Just fyi - I would really like to refactor this module. Ideally, it could be converted to be class-based and it could use a custom resource that checks for the agent by trying to run the executable and evaluating version rather than productid, which has to be updated on every release. It also could support Linux starting in DSCv3.

**Comment by strottos** [comment]
I believe this is now fixed by the latest changes, though a reminder that at some point it'll need publishing to PowerShell Gallery which as far as I can tell it isn't yet.

**Comment by mgreenegit** [comment]
Agreed. I'm working on an additional resource today to handle the new(er) "config" parameter for azcmagent. Hoping for a quick turn-around so I didn't publish 1.1.1.
